name: tkcms_support
description: Tk cms support
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  dev_build: ">=1.1.2+11"
  process_run: ">=1.2.4"

  tekartik_firebase_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      path: packages/firebase_build
    version: '>=0.1.0'
  tekartik_app_node_build_menu:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build_menu
  path: ">=1.9.1"
  tekartik_build_menu_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      path: packages/build_menu_flutter
    version: '>=0.1.0'
  tkcms_common:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      path: packages/tkcms_common
  tekartik_app_csv:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_csv
    version: '>=0.1.3'
  image:
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu_io
  tekartik_firebase_build_menu_flutter:
    git:
      url: https://github.com/tekartik/app_build.dart
      path: packages/firebase_build_menu_flutter
  tekartik_prj_tktools:
    git:
      url: https://github.com/tekartikprj/tktools.git
      path: packages/prj_tktools
  tekartik_firebase_rest:
    git:
      url: https://github.com/tekartik/firebase_rest.dart
      path: firebase_rest

dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.26.2"

  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.15.8'
  collection: ">=1.19.1"
  csv:
  cv: ">=1.1.10"
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
    version: '>=0.9.3'
  http:

_dependency_overrides:
  tekartik_firebase_build:
    path: /home/alex/tekartik/devx/git/github.com/tekartik/app_build.dart/packages/firebase_build
resolution: workspace

