name: tkcms_test
description: Tkcms test
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  tkcms_common:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      path: packages/tkcms_common
  dev_test: ">=1.0.1"
  # path: ^1.8.0

dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.26.2"
resolution: workspace


